# kubectl apply -f service.yml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: frankgallo
spec:
  type: NodePort      
  ports:
  - port: 30002       # Puerto que el Service expondrá
    targetPort: 8080  # Puerto en el contenedor donde tu aplicación escucha
    nodePort: 30002   # Puerto asignado en el nodo, opcional
  selector:
    app: backend  # Debe coincidir con las etiquetas del Deployment