# kubectl apply -f secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: dannalopez
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLW11ZGR5LWR1c3QtYTUyZmNrdmsudXMtZWFzdC0yLmF3cy5uZW9uLnRlY2g6NTQzMi9uZW9uZGI/c3NsbW9kZT1yZXF1aXJl
  DATABASE_USERNAME: bmVvbmRiX293bmVy
  DATABASE_PASSWORD: N25leUJPMEZtcEp0
  API_BACKEND: aHR0cHM6Ly9sYXVnaGluZy1jYXB5YmFyYS00eDdnN3Zwd2c3d2ZwcXgtODA4NS5hcHAuZ2l0aHViLmRldi9jaWNsb1ZpZGE=